### ISSUE TITLE
current release broken with latest mapbox-gl release

### ISSUE THREAD

**Issue by swizardlv** [mapbox/guidance-geojson#7]
Hi please refer to https://github.com/mapbox/mapbox-gl-js/issues/3050

GeoJSONSource is private now and can't new.

guidance-geojson/index.js L316

0.22.0 (August 11 2016)

Breaking Changes

The GeoJSONSource, VideoSource, ImageSource constructors are now private. Please use map.addSource({...}) to create sources and map.getSource(...).setData(...) to update GeoJSON sources. #2667

please help fix thanks.

**Comment by emilymdubois** [comment]
@swizardlv, released v0.3.2 with [`GeoJSONSource` scrubbed](https://github.com/mapbox/guidance-geojson/pull/8).

**Comment by swizardlv** [comment]
thanks @emilymdubois
